apiVersion: v1
data:
  clusterprofile_overrides: |
    cluster_input:
      aci_cni_config:
        aci_config:
          aep: bm-srvrs-calico-aep
      registry:
        image_prefix: quay.io/noirolabs
        image_pull_secret: noiro-docker-registry-secret
        network_operator_version: cko-mvp-1
      aci_config:
        cluster_l3out:
          aep: bm-srvrs-calico-aep
          svi:
            type: floating
            floating_ip: 2.100.101.100/24
            secondary_ip: 2.100.101.254/24
            vlan_id: 13
            mtu: 9000
          bgp:
            peering:
              remote_as_number: 64512
              aci_as_number: 2
        l3out:
          name: sauto_l3out-3
          external_networks:
          - sauto_l3out-3_epg
        vrf:
          name: sauto_l3out-3_vrf
          tenant: common
      net_config:
        node_subnet: 2.100.101.1/24
        pod_subnet: 20.2.0.1/16
        extern_dynamic: 20.3.0.1/16
        cluster_svc_subnet: 10.96.0.0/12
      cko_proxy_config:
        http_proxy: http://proxy.esl.cisco.com:80
        https_proxy: http://proxy.esl.cisco.com:80
        no_proxy: 10.96.0.1
      topology:
       rack:
       - id: 1
         aci_pod_id: 1
         leaf:
         - id: 101
           local_ip: 2.100.101.201
         - id: 102
           local_ip: 2.100.101.202
         node:
         - name: k8sbm2-bm-4
         - name: k8sbm2-bm-5
kind: ConfigMap
metadata:
  labels:
    distro: kubernetes
    location: on-prem
    pod_network: calico
  name: calicoacicluster
  namespace: netop-manager
