apiVersion: netop.mgr/v1alpha1
kind: ClusterInfo
metadata:
  creationTimestamp: "2023-03-20T09:15:03Z"
  finalizers:
  - netop.mgr/finalizer
  generation: 2
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"netop.mgr/finalizer": {}
    manager: ansible-operator
    operation: Update
    time: "2023-03-20T09:15:03Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"3af8b827-a281-42aa-95ea-145897ace54a"}: {}
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:aep: {}
              f:vmm_domain:
                .: {}
                f:mcast_range: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:image_pull_policy: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:ovs_memory_limit: {}
              f:sriov_config: {}
            f:logging:
              .: {}
              f:controller_log_level: {}
              f:hostagent_log_level: {}
              f:opflexagent_log_level: {}
            f:net_config:
              .: {}
              f:extern_static: {}
              f:node_svc_subnet: {}
              f:service_vlan: {}
            f:registry:
              .: {}
              f:aci_containers_controller_version: {}
              f:aci_containers_host_version: {}
              f:cnideploy_version: {}
              f:openvswitch_version: {}
              f:opflex_agent_version: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
              f:vrf: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:physical_domain: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:calico_cni_config: {}
          f:cko_proxy_config: {}
          f:cluster_profile_name: {}
          f:cni: {}
          f:connectivity_checker:
            .: {}
            f:reachability_test_enable:
              .: {}
              f:external_url: {}
              f:periodic_sync: {}
          f:context:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:distro:
            .: {}
            f:flavor: {}
            f:platform: {}
            f:type: {}
          f:fabricinfra:
            .: {}
            f:context: {}
            f:name: {}
            f:type: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config:
            .: {}
            f:cluster_svc_subnet: {}
            f:extern_dynamic: {}
            f:kubeapi_vlan: {}
            f:node_subnet: {}
            f:pod_subnet: {}
          f:operator_config:
            .: {}
            f:mode: {}
            f:target_version: {}
          f:profile: {}
          f:registry: {}
          f:service_mesh_config: {}
          f:topology: {}
    manager: manager
    operation: Update
    time: "2023-03-20T09:15:03Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:config_overrides:
          f:aci_config:
            f:system_id: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2023-03-20T09:15:13Z"
  name: alokk8s23
  namespace: netop-manager
  ownerReferences:
  - apiVersion: netop.mgr/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterProfile
    name: auto-alokk8s23
    uid: 3af8b827-a281-42aa-95ea-145897ace54a
  resourceVersion: "2726"
  uid: 454a8770-5cf2-44b2-97f7-bba6aced01da
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: hypf-aep
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        image_pull_policy: Always
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        ovs_memory_limit: 1Gi
        sriov_config: {}
      logging:
        controller_log_level: debug
        hostagent_log_level: debug
        opflexagent_log_level: debug
      net_config:
        extern_static: 10.4.0.1/24
        node_svc_subnet: 10.5.0.1/24
        service_vlan: 46
      registry:
        aci_containers_controller_version: kmr2-test
        aci_containers_host_version: kmr2-test
        cnideploy_version: kmr2-test
        openvswitch_version: kmr2-test
        opflex_agent_version: kmr2-test
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out:
        external_networks:
        - k8s23_net
        name: k8s23
      physical_domain: {}
      system_id: alokk8s23
      vrf:
        name: k8s23_vrf
        tenant: common
    calico_cni_config: {}
    cko_proxy_config: {}
    cluster_profile_name: auto-alokk8s23
    cni: aci
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    context:
      aep: hypf-aep
      l3out:
        external_networks:
        - k8s23_net
        name: k8s23
      vrf:
        name: k8s23_vrf
        tenant: common
    distro:
      flavor: kubernetes-1.23
      platform: baremetal
      type: kubernetes
    fabricinfra:
      context: context-1
      name: alokk8s23-fabric
      type: aci
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config:
      cluster_svc_subnet: 10.96.0.0/12
      extern_dynamic: 10.3.0.1/24
      kubeapi_vlan: 45
      node_subnet: 192.168.23.1/24
      pod_subnet: 10.2.0.1/16
    operator_config:
      mode: unmanaged
      target_version: 0.9.0
    profile: {}
    registry: {}
    service_mesh_config: {}
    topology: {}
status:
  status: false
