apiVersion: netop.mgr/v1alpha1
kind: ClusterNetworkProfile
metadata:
  annotations:
    notification-controller.netop.mgr/created: "true"
  creationTimestamp: "2023-07-06T06:55:34Z"
  generation: 1
  labels:
    autodetect-cluster.notification-controller.netop.mgr: pallavi
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:notification-controller.netop.mgr/created: {}
        f:labels:
          .: {}
          f:autodetect-cluster.notification-controller.netop.mgr: {}
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:aep: {}
              f:vmm_domain:
                .: {}
                f:encap_type: {}
                f:mcast_range:
                  .: {}
                  f:end: {}
                  f:start: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:allow_pods_external_access: {}
              f:drop_log_config: {}
              f:image_pull_policy: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:ovs_memory_limit: {}
              f:sriov_config: {}
            f:logging:
              .: {}
              f:controller_log_level: {}
              f:hostagent_log_level: {}
              f:opflexagent_log_level: {}
            f:net_config:
              .: {}
              f:extern_static: {}
              f:node_svc_subnet: {}
              f:service_vlan: {}
            f:registry: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
              f:vrf: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:physical_domain: {}
            f:system_id: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:calico_cni_config: {}
          f:cko_proxy_config: {}
          f:connectivity_checker:
            .: {}
            f:reachability_test_enable:
              .: {}
              f:external_url: {}
              f:periodic_sync: {}
          f:context:
            .: {}
            f:l3out: {}
            f:vrf: {}
          f:distro: {}
          f:fabricinfra:
            .: {}
            f:name: {}
            f:type: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config:
            .: {}
            f:extern_dynamic: {}
            f:kubeapi_vlan: {}
            f:node_subnet: {}
            f:pod_subnet: {}
          f:operator_config:
            .: {}
            f:mode: {}
          f:profile: {}
          f:registry: {}
          f:service_mesh_config: {}
          f:topology: {}
    manager: manager
    operation: Update
    time: "2023-07-06T06:55:34Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:ready: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-07-06T06:55:34Z"
  name: auto-pallavi
  namespace: netop-manager
  resourceVersion: "3038"
  uid: 7d6fc03c-3d26-4fe8-bd43-f28a1fb896d9
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: hypf-aep
        vmm_domain:
          encap_type: vxlan
          mcast_range:
            end: 225.32.255.255
            start: 225.32.1.1
          nested_inside: {}
      kube_config:
        allow_pods_external_access: true
        drop_log_config: {}
        image_pull_policy: Always
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        ovs_memory_limit: 1Gi
        sriov_config: {}
      logging:
        controller_log_level: debug
        hostagent_log_level: debug
        opflexagent_log_level: debug
      net_config:
        extern_static: 10.4.0.1/24
        node_svc_subnet: 10.5.0.1/24
        service_vlan: 44
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out:
        external_networks:
        - k8s22_net
        name: k8s22
      physical_domain: {}
      system_id: pallavi
      vrf:
        name: k8s22_vrf
        tenant: common
    calico_cni_config: {}
    cko_proxy_config: {}
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    context:
      l3out: {}
      vrf: {}
    distro: {}
    fabricinfra:
      name: pallavi
      type: aci
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config:
      extern_dynamic: 10.3.0.1/24
      kubeapi_vlan: 43
      node_subnet: 192.168.22.1/24
      pod_subnet: 10.2.0.1/16
    operator_config:
      mode: managed
    profile: {}
    registry: {}
    service_mesh_config: {}
    topology: {}
status:
  ready: true
