apiVersion: netop.mgr/v1alpha1
kind: ClusterGroupProfile
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"netop.mgr/v1alpha1","kind":"ClusterGroupProfile","metadata":{"annotations":{},"labels":{"cni":"aci","distro":"kubernetes","environment":"prod","location":"az02","platform":"esx"},"name":"k8s-prod-acicni-az02","namespace":"netop-manager"},"spec":{"config_overrides":{"cni":"aci","connectivity_checker":{"error_pods_reporting_enable":true,"reachability_test_enable":{"external_url":{"url":"google.com"},"periodic_sync":{"enable_updates":true,"interval":120}},"reachability_tests":["pod_to_pod","pod_to_node","pod_to_clusterIP","pod_to_service","pod_to_LB_VIP","pod_to_NodePort","pod_to_External","node_to_node","node_to_pod","node_to_clusterIP","node_to_LB_VIPx"]},"distro":{"platform":"esx","release":"1.24","type":"kubernetes"},"operator_config":{"target_version":"0.9.1"}},"selector":{"matchLabels":{"fabric":"aci-fab-02","site":"az02"}}}}
  creationTimestamp: "2023-03-23T10:57:03Z"
  generation: 1
  labels:
    cni: aci
    distro: kubernetes
    environment: prod
    location: az02
    platform: esx
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:cni: {}
          f:distro: {}
          f:environment: {}
          f:location: {}
          f:platform: {}
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:cni: {}
          f:connectivity_checker:
            .: {}
            f:error_pods_reporting_enable: {}
            f:reachability_test_enable:
              .: {}
              f:external_url:
                .: {}
                f:url: {}
              f:periodic_sync:
                .: {}
                f:enable_updates: {}
                f:interval: {}
            f:reachability_tests: {}
          f:distro:
            .: {}
            f:platform: {}
            f:release: {}
            f:type: {}
          f:operator_config:
            .: {}
            f:mode: {}
            f:target_version: {}
        f:selector: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-03-23T10:57:03Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:mode: {}
        f:state: {}
        f:target_version: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-03-23T10:57:03Z"
  name: k8s-prod-acicni-az02
  namespace: netop-manager
  resourceVersion: "343319"
  uid: 58dfafe5-7969-464d-932d-6fe8447e5cc4
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config: {}
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out: {}
      physical_domain: {}
      vrf: {}
    calico_cni_config: {}
    cko_proxy_config: {}
    cni: aci
    connectivity_checker:
      error_pods_reporting_enable: true
      reachability_test_enable:
        external_url:
          url: google.com
        periodic_sync:
          enable_updates: true
          interval: 120
      reachability_tests:
      - pod_to_pod
      - pod_to_node
      - pod_to_clusterIP
      - pod_to_service
      - pod_to_LB_VIP
      - pod_to_NodePort
      - pod_to_External
      - node_to_node
      - node_to_pod
      - node_to_clusterIP
      - node_to_LB_VIPx
    context:
      l3out: {}
      vrf: {}
    distro:
      platform: esx
      release: "1.24"
      type: kubernetes
    fabricinfra: {}
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config: {}
    operator_config:
      mode: managed
      target_version: 0.9.1
    profile: {}
    registry: {}
    service_mesh_config: {}
    topology: {}
  selector:
    matchLabels:
      fabric: aci-fab-02
      site: az02
status:
  mode: managed
  state: true
  target_version: 0.9.1
