apiVersion: netop.mgr/v1alpha1
kind: ClusterInfo
metadata:
  creationTimestamp: "2023-07-12T07:30:50Z"
  finalizers:
  - netop.mgr/finalizer
  generation: 1
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"netop.mgr/finalizer": {}
    manager: ansible-operator
    operation: Update
    time: "2023-07-12T07:30:50Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"216b88d1-a86b-4e2e-8505-0d0a3b24f308"}: {}
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:aep: {}
              f:vmm_domain:
                .: {}
                f:encap_type: {}
                f:mcast_range:
                  .: {}
                  f:end: {}
                  f:start: {}
                f:nested_inside:
                  .: {}
                  f:elag_name: {}
                  f:installer_provisioned_lb_ip: {}
                  f:name: {}
                  f:type: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:image_pull_policy: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:ovs_memory_limit: {}
              f:sriov_config: {}
            f:logging:
              .: {}
              f:controller_log_level: {}
              f:hostagent_log_level: {}
              f:opflexagent_log_level: {}
            f:net_config:
              .: {}
              f:extern_static: {}
              f:node_svc_subnet: {}
              f:service_vlan: {}
            f:registry:
              .: {}
              f:acc_provision_operator_version: {}
              f:aci_containers_controller_version: {}
              f:aci_containers_host_version: {}
              f:aci_containers_operator_version: {}
              f:cnideploy_version: {}
              f:openvswitch_version: {}
              f:opflex_agent_version: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
              f:vrf: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:physical_domain: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:calico_cni_config: {}
          f:cko_proxy_config:
            .: {}
            f:http_proxy: {}
            f:https_proxy: {}
            f:no_proxy: {}
          f:cluster_profile_name: {}
          f:cni: {}
          f:connectivity_checker:
            .: {}
            f:reachability_test_enable:
              .: {}
              f:external_url: {}
              f:periodic_sync: {}
          f:context:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:distro:
            .: {}
            f:flavor: {}
            f:platform: {}
            f:release: {}
            f:type: {}
          f:fabricinfra:
            .: {}
            f:name: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config:
            .: {}
            f:cluster_svc_subnet: {}
            f:extern_dynamic: {}
            f:kubeapi_vlan: {}
            f:node_subnet: {}
            f:pod_subnet: {}
          f:operator_config:
            .: {}
            f:mode: {}
            f:target_version: {}
          f:profile: {}
          f:registry:
            .: {}
            f:image_prefix: {}
            f:network_operator_version: {}
          f:service_mesh_config: {}
          f:topology: {}
    manager: manager
    operation: Update
    time: "2023-07-12T07:30:50Z"
  name: ocp410gf
  namespace: netop-manager
  ownerReferences:
  - apiVersion: netop.mgr/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterProfile
    name: ocp410gf
    uid: 216b88d1-a86b-4e2e-8505-0d0a3b24f308
  resourceVersion: "162982"
  uid: 813554f1-97b6-4b33-9b95-73bddf0c79f1
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: fab20-esx
        vmm_domain:
          encap_type: vxlan
          mcast_range:
            end: 225.20.255.255
            start: 225.20.1.1
          nested_inside:
            elag_name: Fab20_ELAG
            installer_provisioned_lb_ip: 192.168.2.2
            name: HX-vC
            type: vmware
      kube_config:
        drop_log_config: {}
        image_pull_policy: Always
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        ovs_memory_limit: 1Gi
        sriov_config: {}
      logging:
        controller_log_level: debug
        hostagent_log_level: debug
        opflexagent_log_level: debug
      net_config:
        extern_static: 10.4.0.1/24
        node_svc_subnet: 10.5.0.1/24
        service_vlan: 203
      registry:
        acc_provision_operator_version: kmr2-test
        aci_containers_controller_version: kmr2-test
        aci_containers_host_version: kmr2-test
        aci_containers_operator_version: kmr2-test
        cnideploy_version: kmr2-test
        openvswitch_version: kmr2-test
        opflex_agent_version: kmr2-test
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out:
        external_networks:
        - ocp-gf-l3-extepg
        name: ocp410_gf_l3out
      physical_domain: {}
      vrf:
        name: ocp410_gf_vrf
        tenant: common
    calico_cni_config: {}
    cko_proxy_config:
      http_proxy: http://proxy.myorg.com:80
      https_proxy: http://proxy.myorg.com:80
      no_proxy: localhost,127.0.0.1
    cluster_profile_name: ocp410gf
    cni: aci
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    context:
      aep: fab20-esx
      l3out:
        external_networks:
        - ocp-gf-l3-extepg
        name: ocp410_gf_l3out
      vrf:
        name: ocp410_gf_vrf
        tenant: common
    distro:
      flavor: openshift-4.10-esx
      platform: esx
      release: "4.10"
      type: openshift
    fabricinfra:
      name: ocp410gf
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config:
      cluster_svc_subnet: 10.96.0.0/12
      extern_dynamic: 10.3.0.1/24
      kubeapi_vlan: 202
      node_subnet: 192.168.2.1/24
      pod_subnet: 10.2.0.1/16
    operator_config:
      mode: managed
      target_version: 0.9.1
    profile: {}
    registry:
      image_prefix: quay.io/cko
      network_operator_version: 0.9.1.d04f56f
    service_mesh_config: {}
    topology: {}
status:
  status: false
