apiVersion: netop.mgr/v1alpha1
kind: ClusterInfo
metadata:
  creationTimestamp: "2023-03-21T09:29:05Z"
  finalizers:
  - netop.mgr/finalizer
  generation: 2
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"netop.mgr/finalizer": {}
    manager: ansible-operator
    operation: Update
    time: "2023-03-21T09:29:05Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"62cf602c-d5f9-4c00-a7fb-94a89e996e65"}: {}
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:aep: {}
              f:vmm_domain:
                .: {}
                f:encap_type: {}
                f:mcast_range:
                  .: {}
                  f:end: {}
                  f:start: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:sriov_config: {}
            f:logging: {}
            f:net_config:
              .: {}
              f:extern_static: {}
              f:node_svc_subnet: {}
              f:service_vlan: {}
            f:registry: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
              f:vrf: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:physical_domain: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:calico_cni_config: {}
          f:cko_proxy_config: {}
          f:cluster_profile_name: {}
          f:cni: {}
          f:connectivity_checker:
            .: {}
            f:error_pods_reporting_enable: {}
            f:reachability_test_enable:
              .: {}
              f:external_url:
                .: {}
                f:url: {}
              f:periodic_sync:
                .: {}
                f:enable_updates: {}
                f:interval: {}
            f:reachability_tests: {}
          f:context:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:distro:
            .: {}
            f:flavor: {}
            f:platform: {}
            f:release: {}
            f:type: {}
          f:fabricinfra:
            .: {}
            f:name: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config:
            .: {}
            f:cluster_svc_subnet: {}
            f:extern_dynamic: {}
            f:kubeapi_vlan: {}
            f:node_subnet: {}
            f:pod_subnet: {}
          f:operator_config:
            .: {}
            f:mode: {}
            f:target_version: {}
          f:profile: {}
          f:registry: {}
          f:service_mesh_config: {}
          f:topology: {}
    manager: manager
    operation: Update
    time: "2023-03-21T09:29:05Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:config_overrides:
          f:aci_config:
            f:system_id: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2023-03-21T09:29:11Z"
  name: ocp410gf
  namespace: netop-manager
  ownerReferences:
  - apiVersion: netop.mgr/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterProfile
    name: ocp410gf-clusterprofile
    uid: 62cf602c-d5f9-4c00-a7fb-94a89e996e65
  resourceVersion: "1421"
  uid: 450dcbfc-9db6-461b-a897-638f3b813f92
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: fab20-esx
        vmm_domain:
          encap_type: vxlan
          mcast_range:
            end: 225.20.255.255
            start: 225.20.0.1
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config:
        extern_static: 10.4.0.1/24
        node_svc_subnet: 192.168.2.1/24
        service_vlan: 203
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out:
        external_networks:
        - ocp-gf-l3-extepg
        name: ocp410_gf_l3out
      physical_domain: {}
      system_id: ocp410gf
      vrf:
        name: ocp410_gf_vrf
        tenant: common
    calico_cni_config: {}
    cko_proxy_config: {}
    cluster_profile_name: ocp410gf-clusterprofile
    cni: aci
    connectivity_checker:
      error_pods_reporting_enable: true
      reachability_test_enable:
        external_url:
          url: google.com
        periodic_sync:
          enable_updates: true
          interval: 120
      reachability_tests:
      - pod_to_pod
      - pod_to_node
      - pod_to_clusterIP
      - pod_to_service
      - pod_to_LB_VIP
      - pod_to_NodePort
      - pod_to_External
      - node_to_node
      - node_to_pod
      - node_to_clusterIP
      - node_to_LB_VIP
    context:
      aep: fab20-esx
      l3out:
        external_networks:
        - ocp-gf-l3-extepg
        name: ocp410_gf_l3out
      vrf:
        name: ocp410_gf_vrf
        tenant: common
    distro:
      flavor: openshift-4.10-esx
      platform: esx
      release: "4.10"
      type: openshift
    fabricinfra:
      name: ocp410gf
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config:
      cluster_svc_subnet: 10.96.0.0/12
      extern_dynamic: 10.3.0.1/24
      kubeapi_vlan: 202
      node_subnet: 10.5.0.1/24
      pod_subnet: 10.2.0.1/16
    operator_config:
      mode: managed
      target_version: 0.9.1
    profile: {}
    registry: {}
    service_mesh_config: {}
    topology: {}
status:
  status: false
