apiVersion: netop.mgr/v1alpha1
kind: FabricInfra
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"netop.mgr/v1alpha1","kind":"FabricInfra","metadata":{"annotations":{},"labels":{"fabric":"4.2.7f","site":"BUILDING-15-LAB"},"name":"ocp410gf","namespace":"netop-manager"},"spec":{"bgp":{"aci_as_number":2,"remote_as_numbers":[64512]},"contexts":{"context-1":{"aep":"fab20-esx","l3out":{"external_networks":["ocp-gf-l3-extepg"],"name":"ocp410_gf_l3out"},"vrf":{"name":"ocp410_gf_vrf","tenant":"common"}}},"credentials":{"hosts":["10.30.120.61"],"secretRef":{"name":"apic-credentials"}},"external_subnets":["10.3.0.1/24","10.4.0.1/24"],"fabric_type":"aci","infra_vlan":4093,"internal_subnets":["10.5.0.1/16","192.168.2.1/24"],"mcast_subnets":["225.20.0.0/16"],"topology":{"rack":[{"aci_pod_id":1,"id":1,"leaf":[{"id":101},{"id":102}],"node":[{"name":"k8s-node1"},{"name":"k8s-node2"}]},{"aci_pod_id":1,"id":2,"leaf":[{"id":103},{"id":104}],"node":[{"name":"k8s-node3"},{"name":"k8s-node4"}]}]},"vlans":[202,203]}}
  creationTimestamp: "2023-04-06T10:34:59Z"
  finalizers:
  - fabricinfra.netop.mgr/finalizer
  generation: 1
  labels:
    fabric: 4.2.7f
    site: BUILDING-15-LAB
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:fabric: {}
          f:site: {}
      f:spec:
        .: {}
        f:bgp:
          .: {}
          f:aci_as_number: {}
          f:remote_as_numbers: {}
        f:contexts:
          .: {}
          f:context-1:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
        f:credentials:
          .: {}
          f:hosts: {}
          f:secretRef:
            .: {}
            f:name: {}
        f:external_subnets: {}
        f:fabric_type: {}
        f:infra_vlan: {}
        f:internal_subnets: {}
        f:mcast_subnets: {}
        f:topology:
          .: {}
          f:rack: {}
        f:vlans: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-04-06T10:34:59Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"fabricinfra.netop.mgr/finalizer": {}
    manager: manager
    operation: Update
    time: "2023-04-06T10:34:59Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:available:
          .: {}
          f:contexts:
            .: {}
            f:context-1:
              .: {}
              f:aep: {}
              f:l3out:
                .: {}
                f:external_networks: {}
                f:name: {}
              f:vrf:
                .: {}
                f:name: {}
                f:tenant: {}
          f:external_subnets: {}
          f:internal_subnets: {}
          f:mcast_subnets: {}
          f:remote_as_numbers: {}
          f:vlans: {}
        f:ready: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-04-06T10:34:59Z"
  name: ocp410gf
  namespace: netop-manager
  resourceVersion: "8431"
  uid: 005d04be-d12a-43b8-b89c-b5f00825902e
spec:
  bgp:
    aci_as_number: 2
    remote_as_numbers:
    - 64512
  contexts:
    context-1:
      aep: fab20-esx
      l3out:
        external_networks:
        - ocp-gf-l3-extepg
        name: ocp410_gf_l3out
      vrf:
        name: ocp410_gf_vrf
        tenant: common
  credentials:
    hosts:
    - 10.30.120.61
    secretRef:
      name: apic-credentials
  external_subnets:
  - 10.3.0.1/24
  - 10.4.0.1/24
  fabric_type: aci
  infra_vlan: 4093
  internal_subnets:
  - 10.5.0.1/16
  - 192.168.2.1/24
  mcast_subnets:
  - 225.20.0.0/16
  topology:
    rack:
    - aci_pod_id: 1
      id: 1
      leaf:
      - id: 101
      - id: 102
      node:
      - name: k8s-node1
      - name: k8s-node2
    - aci_pod_id: 1
      id: 2
      leaf:
      - id: 103
      - id: 104
      node:
      - name: k8s-node3
      - name: k8s-node4
  vlans:
  - 202
  - 203
status:
  available:
    contexts:
      context-1:
        aep: fab20-esx
        l3out:
          external_networks:
          - ocp-gf-l3-extepg
          name: ocp410_gf_l3out
        vrf:
          name: ocp410_gf_vrf
          tenant: common
    external_subnets:
    - 10.3.0.1/24
    - 10.4.0.1/24
    internal_subnets:
    - 10.5.0.1/16
    - 192.168.2.1/24
    mcast_subnets:
    - 225.20.0.0/16
    remote_as_numbers:
    - 64512
    vlans:
    - 202
    - 203
  ready: true
