apiVersion: netop.mgr/v1alpha1
kind: FabricInfra
metadata:
  creationTimestamp: "2023-05-03T09:40:12Z"
  finalizers:
  - fabricinfra.netop.mgr/finalizer
  generation: 1
  labels:
    cisco_app: cisco_03_05_2023_05_40_12_060524_UZYGAR
    fabric: on-prem-dev-infra
    purpose: testing
    site: bldg-15-lab
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:cisco_app: {}
          f:fabric: {}
          f:purpose: {}
          f:site: {}
      f:spec:
        .: {}
        f:bgp:
          .: {}
          f:aci_as_number: {}
          f:remote_as_numbers: {}
        f:contexts:
          .: {}
          f:context-1:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
        f:credentials:
          .: {}
          f:hosts: {}
          f:secretRef:
            .: {}
            f:name: {}
        f:external_subnets: {}
        f:fabric_type: {}
        f:infra_vlan: {}
        f:internal_subnets: {}
        f:mcast_subnets: {}
        f:topology:
          .: {}
          f:rack: {}
        f:vlans: {}
    manager: kubectl-create
    operation: Update
    time: "2023-05-03T09:40:12Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"fabricinfra.netop.mgr/finalizer": {}
    manager: manager
    operation: Update
    time: "2023-05-03T09:40:12Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:allocated: {}
        f:available:
          .: {}
          f:internal_subnets: {}
          f:mcast_subnets: {}
          f:remote_as_numbers: {}
        f:discovered_infra_vlan: {}
        f:ready: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-05-03T09:57:45Z"
  name: pallavi23
  namespace: netop-manager
  resourceVersion: "6662"
  uid: d035e190-eb63-4b08-8749-824fdca0836e
spec:
  bgp:
    aci_as_number: 2
    remote_as_numbers:
    - 64512
  contexts:
    context-1:
      aep: hypf-aep
      l3out:
        external_networks:
        - k8s23_net
        name: k8s23
      vrf:
        name: k8s23_vrf
        tenant: common
  credentials:
    hosts:
    - 10.30.120.180
    secretRef:
      name: apic-credentials
  external_subnets:
  - 10.3.0.1/24
  - 10.4.0.1/24
  fabric_type: aci
  infra_vlan: 3901
  internal_subnets:
  - 10.5.0.1/16
  - 192.168.23.1/24
  mcast_subnets:
  - 225.33.0.0/16
  topology:
    rack:
    - aci_pod_id: 1
      id: 1
      leaf:
      - id: 101
      - id: 102
      node:
      - name: k8s-node1
      - name: k8s-node2
    - aci_pod_id: 1
      id: 2
      leaf:
      - id: 103
      - id: 104
      node:
      - name: k8s-node3
      - name: k8s-node4
  vlans:
  - 45
  - 46
status:
  allocated:
  - cluster_profile: auto-pallavi23
    context:
      aep: hypf-aep
      l3out:
        external_networks:
        - k8s23_net
        name: k8s23
      vrf:
        name: k8s23_vrf
        tenant: common
    external_subnets:
    - 10.3.0.1/24
    - 10.4.0.1/24
    internal_subnets:
    - 192.168.23.1/24
    - 10.5.0.1/24
    vlans:
    - 45
    - 46
  available:
    internal_subnets:
    - 10.5.0.1/16
    mcast_subnets:
    - 225.33.0.0/16
    remote_as_numbers:
    - 64512
  discovered_infra_vlan: 3901
  ready: true
