apiVersion: netop.mgr/v1alpha1
kind: FabricInfra
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"netop.mgr/v1alpha1","kind":"FabricInfra","metadata":{"annotations":{},"labels":{"fabric":"on-prem-dev-infra","purpose":"testing","site":"bldg-15-lab"},"name":"pallavi","namespace":"netop-manager"},"spec":{"credentials":{"hosts":["10.30.120.180"],"secretRef":{"name":"apic-credentials"}},"fabric_type":"aci","infra_vlan":3901}}
  creationTimestamp: "2023-07-06T06:52:10Z"
  finalizers:
  - fabricinfra.netop.mgr/finalizer
  generation: 2
  labels:
    fabric: on-prem-dev-infra
    purpose: testing
    site: bldg-15-lab
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:fabric: {}
          f:purpose: {}
          f:site: {}
      f:spec:
        .: {}
        f:credentials:
          .: {}
          f:hosts: {}
          f:secretRef:
            .: {}
            f:name: {}
        f:fabric_type: {}
        f:infra_vlan: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-07-06T06:52:10Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"fabricinfra.netop.mgr/finalizer": {}
      f:spec:
        f:bgp: {}
        f:topology: {}
    manager: manager
    operation: Update
    time: "2023-07-06T06:52:10Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:allocated: {}
        f:available: {}
        f:discovered_infra_vlan: {}
        f:ready: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-07-06T09:05:27Z"
  name: pallavi
  namespace: netop-manager
  resourceVersion: "23305"
  uid: 4b621978-c08d-4343-b719-9b78e4c19369
spec:
  bgp: {}
  credentials:
    hosts:
    - 10.30.120.180
    secretRef:
      name: apic-credentials
  fabric_type: aci
  infra_vlan: 3901
  topology: {}
status:
  allocated:
  - cluster_profile: auto-pallavi
    context:
      aep: hypf-aep
      l3out:
        external_networks:
        - k8s22_net
        name: k8s22
      vrf:
        name: k8s22_vrf
        tenant: common
    external_subnets:
    - 10.3.0.1/24
    - 10.4.0.1/24
    internal_subnets:
    - 192.168.22.1/24
    - 10.5.0.1/24
    vlans:
    - 43
    - 44
  available: {}
  discovered_infra_vlan: 3901
  ready: true
