apiVersion: netop.mgr/v1alpha1
kind: ClusterProfile
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"netop.mgr/v1alpha1","kind":"ClusterProfile","metadata":{"annotations":{},"name":"pallavi23","namespace":"netop-manager"},"spec":{"cni":"aci"}}
  creationTimestamp: "2023-07-04T11:05:37Z"
  finalizers:
  - clusterprofile.netop.mgr/finalizer
  generation: 2
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:cni: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-07-04T11:05:37Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"clusterprofile.netop.mgr/finalizer": {}
      f:spec:
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:vmm_domain:
                .: {}
                f:mcast_range: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:sriov_config: {}
            f:logging: {}
            f:net_config: {}
            f:registry: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
              f:vrf: {}
            f:l3out: {}
            f:physical_domain: {}
            f:vrf: {}
          f:calico_cni_config: {}
          f:cko_proxy_config: {}
          f:connectivity_checker:
            .: {}
            f:reachability_test_enable:
              .: {}
              f:external_url: {}
              f:periodic_sync: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config: {}
          f:registry: {}
          f:service_mesh_config: {}
        f:distro: {}
        f:fabricinfra: {}
        f:operator_config:
          .: {}
          f:mode: {}
    manager: manager
    operation: Update
    time: "2023-07-04T11:05:37Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:aci_cni_config: {}
        f:assigned_subnets:
          .: {}
          f:cluster_svc_subnet: {}
          f:extern_dynamic: {}
          f:extern_static: {}
          f:node_subnet: {}
          f:node_svc_subnet: {}
          f:pod_subnet: {}
        f:calico_cni_config: {}
        f:cluster_group_profile_name: {}
        f:context:
          .: {}
          f:aep: {}
          f:l3out:
            .: {}
            f:external_networks: {}
            f:name: {}
          f:vrf:
            .: {}
            f:name: {}
            f:tenant: {}
        f:fabricinfra:
          .: {}
          f:context: {}
          f:name: {}
        f:mcast_subnets: {}
        f:node_vlan: {}
        f:operator_config:
          .: {}
          f:mode: {}
        f:ready: {}
        f:vlans: {}
        f:workload_cluster_manifest_locations: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-07-04T11:05:42Z"
  name: pallavi23
  namespace: netop-manager
  resourceVersion: "8168"
  uid: e197df50-1022-40b0-a67c-b11252015e3a
spec:
  cni: aci
  config_overrides:
    aci_cni_config:
      aci_config:
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config: {}
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out: {}
      physical_domain: {}
      vrf: {}
    calico_cni_config: {}
    cko_proxy_config: {}
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config: {}
    registry: {}
    service_mesh_config: {}
  distro: {}
  fabricinfra: {}
  operator_config:
    mode: managed
status:
  aci_cni_config: {}
  assigned_subnets:
    cluster_svc_subnet: 10.96.0.0/12
    extern_dynamic: 10.3.0.1/24
    extern_static: 10.4.0.1/24
    node_subnet: 10.5.0.1/24
    node_svc_subnet: 192.168.23.1/24
    pod_subnet: 10.2.0.1/16
  calico_cni_config: {}
  cluster_group_profile_name: default-cluster-group-profile-aci
  context:
    aep: hypf-aep
    l3out:
      external_networks:
      - k8s23_net
      name: k8s23
    vrf:
      name: k8s23_vrf
      tenant: common
  fabricinfra:
    context: context-1
    name: pallavi23
  mcast_subnets:
  - 225.33.0.0/16
  node_vlan: 45
  operator_config:
    mode: managed
  ready: true
  vlans:
  - 45
  - 46
  workload_cluster_manifest_locations:
  - 'argo: https://github.com/networkoperator/demo-cluster-manifests/tree/pallavi_k8s23_greenfield/workload/argo/pallavi23'
  - 'operator: https://github.com/networkoperator/demo-cluster-manifests/tree/pallavi_k8s23_greenfield/workload/config/pallavi23'
