apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netop-fabric-manager
  namespace: netop-manager
spec:
  destination:
    namespace: netop-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workload/config/oshift2/
    repoURL: https://github.com/networkoperator/demo-cluster-manifests
    targetRevision: sumit-test-1 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Replace=true