apiVersion: v1
data:
  status: |-
    {
      "cStatus": {
        "test-conn-check": "{UpdatedAt:2023-11-10 06:20:36.188360154 +0000 UTC Results:{PodToPod:Fail PodToNode:Fail PodToClusterIp:Pass PodToService:Pass PodToLbVip:Fail PodToNodePort:Fail PodToExternal:Fail NodeToNode:Pass NodeToPod:Pass NodeToClusterIp:Pass NodeToLbVip:Pass NodeToNodePort: NodeToExternal:} ResultCount:{Passed:6 Failed:5 Skipped:2}}"
      },
      "conditions": {
        "lastTransitionTime": "2023-11-16T05:16:51Z",
        "message": "diagnosticops tool monitored successfully",
        "reason": "OperatorRunning",
        "status": "True",
        "type": "Available"
      },
      "observedGeneration": 1,
      "state": "Running"
    }
  status_b64: |-
    eyAiY1N0YXR1cyI6IHsgInRlc3QtY29ubi1jaGVjayI6ICJ7VXBkYXRlZEF0OjIwMjMtMTEtMTAgMDY6
    MjA6MzYuMTg4MzYwMTU0ICswMDAwIFVUQyBSZXN1bHRzOntQb2RUb1BvZDpGYWlsIFBvZFRvTm9kZTpG
    YWlsIFBvZFRvQ2x1c3RlcklwOlBhc3MgUG9kVG9TZXJ2aWNlOlBhc3MgUG9kVG9MYlZpcDpGYWlsIFBv
    ZFRvTm9kZVBvcnQ6RmFpbCBQb2RUb0V4dGVybmFsOkZhaWwgTm9kZVRvTm9kZTpQYXNzIE5vZGVUb1Bv
    ZDpQYXNzIE5vZGVUb0NsdXN0ZXJJcDpQYXNzIE5vZGVUb0xiVmlwOlBhc3MgTm9kZVRvTm9kZVBvcnQ6
    IE5vZGVUb0V4dGVybmFsOn0gUmVzdWx0Q291bnQ6e1Bhc3NlZDo2IEZhaWxlZDo1IFNraXBwZWQ6Mn19
    IiB9LCAiY29uZGl0aW9ucyI6IHsgImxhc3RUcmFuc2l0aW9uVGltZSI6ICIyMDIzLTExLTE2VDA1OjE2
    OjUxWiIsICJtZXNzYWdlIjogImRpYWdub3N0aWNvcHMgdG9vbCBtb25pdG9yZWQgc3VjY2Vzc2Z1bGx5
    IiwgInJlYXNvbiI6ICJPcGVyYXRvclJ1bm5pbmciLCAic3RhdHVzIjogIlRydWUiLCAidHlwZSI6ICJB
    dmFpbGFibGUiIH0sICJvYnNlcnZlZEdlbmVyYXRpb24iOiAxLCAic3RhdGUiOiAiUnVubmluZyIgfQo=
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: cko-diagnostic-connectivity-checker
  name: pallavi23-cko-diagnostic-connectivity-checker
  namespace: 
