apiVersion: v1
data:
  status: |-
    {
      "observedGeneration": 1,
      "state": "Running"
    }
  status_b64: eyAib2JzZXJ2ZWRHZW5lcmF0aW9uIjogMSwgInN0YXRlIjogIlJ1bm5pbmciIH0K
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: cko-diagnostic-connectivity-checker
  name: pallavi23-cko-diagnostic-connectivity-checker
  namespace: 
