apiVersion: v1
data:
  installer-aci-cni.yaml: |
    "name:installer-aci-cni, ns:null, status:{\"componentStatus\":{\"cko-cni\":{\"lastUpdated\":\"171717-317-170 317:03:03\",\"mode\":\"managed\",\"type\":\"cko-cni-aci\"}},\"observedGeneration\":1,\"operatorStatus\":\"Running\"}, status_b64:eyJjb21wb25lbnRTdGF0dXMiOnsiY2tvLWNuaSI6eyJsYXN0VXBkYXRlZCI6IjE3MTcxNy0zMTctMTcwIDMxNzowMzowMyIsIm1vZGUiOiJtYW5hZ2VkIiwidHlwZSI6ImNrby1jbmktYWNpIn19LCJvYnNlcnZlZEdlbmVyYXRpb24iOjEsIm9wZXJhdG9yU3RhdHVzIjoiUnVubmluZyJ9"
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: installer-aci-cni
  name: alok-installer-aci-cni
  namespace: 
