apiVersion: v1
data:
  data: name:installer-platform, ns:null, status:{"componentStatus":{"cko-diagnostic":{"lastUpdated":"282828-328-280
    328:03:03","mode":"managed","type":"connectivity-checker"},"cko-gitops":{"lastUpdated":"282828-328-280
    328:03:03","mode":"managed","type":"argo"}},"observedGeneration":1,"operatorStatus":"Running"},
    status_b64:eyJjb21wb25lbnRTdGF0dXMiOnsiY2tvLWRpYWdub3N0aWMiOnsibGFzdFVwZGF0ZWQiOiIyODI4MjgtMzI4LTI4MCAzMjg6MDM6MDMiLCJtb2RlIjoibWFuYWdlZCIsInR5cGUiOiJjb25uZWN0aXZpdHktY2hlY2tlciJ9LCJja28tZ2l0b3BzIjp7Imxhc3RVcGRhdGVkIjoiMjgyODI4LTMyOC0yODAgMzI4OjAzOjAzIiwibW9kZSI6Im1hbmFnZWQiLCJ0eXBlIjoiYXJnbyJ9fSwib2JzZXJ2ZWRHZW5lcmF0aW9uIjoxLCJvcGVyYXRvclN0YXR1cyI6IlJ1bm5pbmcifQ==
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    netop-manager-resource: installer.controller.netop-manager.io
    notification.notification-ctrlr.netop-manager.io: exclude
  name: alok-installer.controller.netop-manager.io
  namespace: netop-manager-system
