apiVersion: v1
data:
  data: name:installer-calico-cni, ns:null, status:{"componentStatus":{"cko-cni":{"lastUpdated":"6066-26-60
    26:02:02","mode":"unmanaged","type":"cko-cni-calico"}},"observedGeneration":1,"operatorStatus":"Running"},
    status_b64:eyJjb21wb25lbnRTdGF0dXMiOnsiY2tvLWNuaSI6eyJsYXN0VXBkYXRlZCI6IjYwNjYtMjYtNjAgMjY6MDI6MDIiLCJtb2RlIjoidW5tYW5hZ2VkIiwidHlwZSI6ImNrby1jbmktY2FsaWNvIn19LCJvYnNlcnZlZEdlbmVyYXRpb24iOjEsIm9wZXJhdG9yU3RhdHVzIjoiUnVubmluZyJ9
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    netop-manager-resource: installer.controller.netop-manager.io
    notification.notification-ctrlr.netop-manager.io: exclude
  name: bm2calico-installer.controller.netop-manager.io
  namespace: netop-manager-system
