apiVersion: v1
data:
  fabricinfras.netop.mgr.yaml: |
    "name:hyperflex, ns:netop-manager, status:{\"allocated\":[{\"external_subnets\":[\"10.3.0.1/24\",\"10.4.0.1/24\"],\"internal_subnets\":[\"10.2.0.1/16\",\"10.5.0.1/16\",\"192.168.57.1/24\"],\"machine_group_profile\":\"k8s-1.21\",\"mcast_subnets\":[\"225.91.0.0/16\"],\"vlans\":[291,292]}],\"deployment_scripts\":[\"kubectl apply -f https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/sumit-test-1/fabric-manager/argo/hyperflex/argo_app.yaml\"],\"ready\":true}, status_b64:eyJhbGxvY2F0ZWQiOlt7ImV4dGVybmFsX3N1Ym5ldHMiOlsiMTAuMy4wLjEvMjQiLCIxMC40LjAuMS8yNCJdLCJpbnRlcm5hbF9zdWJuZXRzIjpbIjEwLjIuMC4xLzE2IiwiMTAuNS4wLjEvMTYiLCIxOTIuMTY4LjU3LjEvMjQiXSwibWFjaGluZV9ncm91cF9wcm9maWxlIjoiazhzLTEuMjEiLCJtY2FzdF9zdWJuZXRzIjpbIjIyNS45MS4wLjAvMTYiXSwidmxhbnMiOlsyOTEsMjkyXX1dLCJkZXBsb3ltZW50X3NjcmlwdHMiOlsia3ViZWN0bCBhcHBseSAtZiBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vbmV0d29ya29wZXJhdG9yL2RlbW8tY2x1c3Rlci1tYW5pZmVzdHMvc3VtaXQtdGVzdC0xL2ZhYnJpYy1tYW5hZ2VyL2FyZ28vaHlwZXJmbGV4L2FyZ29fYXBwLnlhbWwiXSwicmVhZHkiOnRydWV9"
kind: ConfigMap
metadata:
  labels:
    netop-manager: fabricinfras.netop.mgr
  name: fabricinfras.netop.mgr
  namespace: netop-manager
