apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netop-manager
  namespace: netop-manager-system
spec:
  destination:
    namespace: netop-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workload/config/ocp410bf/
    repoURL: https://github.com/networkoperator/demo-cluster-manifests
    targetRevision: pallavi_cko
    directory:
      exclude: '*.tar.gz'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Replace=true