
apiVersion: controller.netop-manager.io/v1alpha1
kind: Installer
metadata:
  name: installer-sample-networking
  namespace: netop-manager-system
spec:
  networkFunctions:
    networking:
      cko-cni:
        version: "5.2.3.3"
        type: "aci-cni"
        managedComponent: true
        options:
          aci-cni-specs: YXBpVmVyc2lvbjogdjEKa2luZDogUG9kCm1ldGFkYXRhOgogIG5hbWU6IGJ1c3lib3gKICBuYW1lc3BhY2U6IGRlZmF1bHQKc3BlYzoKICBjb250YWluZXJzOgogIC0gaW1hZ2U6IGJ1c3lib3gKICAgIGNvbW1hbmQ6CiAgICAgIC0gc2xlZXAKICAgICAgLSAiMzYwMCIKICAgIGltYWdlUHVsbFBvbGljeTogSWZOb3RQcmVzZW50CiAgICBuYW1lOiBidXN5Ym94CiAgcmVzdGFydFBvbGljeTogQWx3YXlz