apiVersion: v1
data:
  clusterprofile_overrides: "machine_group_profile_name: k8s-1.21\ncluster_input:\n
    \ aci_cni_config:\n    aci_config:\n      vmm_domain:\n        encap_type: vxlan\n
    \       mcast_range:\n            start: 225.114.1.1\n            end: 225.114.255.255\n
    \   kube_config:\n      allow_pods_external_access: True\n    logging:\n      controller_log_level:
    debug\n      hostagent_log_level: debug\n      opflexagent_log_level: debug\n
    \   net_config:\n      extern_static: 10.4.112.1/21\n      service_vlan: 102\n
    \     node_svc_subnet: 10.5.112.1/21\n  registry:\n    image_prefix: quay.io/noirolabs\n
    \   image_pull_secret: noiro-docker-registry-secret\n  net_config:\n    node_subnet:
    1.100.101.1/24\n    pod_subnet: 10.2.0.1/16\n    extern_dynamic: 10.3.112.1/21\n
    \   kubeapi_vlan: 101\n    cluster_svc_subnet: 10.96.0.0/12\n    kubeconfig: https://127.0.0.1:6443
    \n  monitoring_config:\n    monitoring_type: prometheus\n    remote_write_ip:
    3.237.37.136\n    remote_write_port: 32307\n  cko_proxy_config:\n    http_proxy:
    http://proxy.esl.cisco.com:80\n    https_proxy: http://proxy.esl.cisco.com:80\n
    \   no_proxy: 10.96.0.0/12\n"
kind: ConfigMap
metadata:
  labels:
    cluster: cluster-1
  name: fab14c1
  namespace: netop-manager
