apiVersion: netop.mgr/v1
kind: ClusterProfile
metadata:
  name: fab14c1
  namespace: netop-manager
spec:
  cluster_input:
    cni:
      target_version: 5.2.3.3
    profile:
      cni: kubernetes-1.22
      loadbalancer: fabric
  selector:
    matchLabels:
      computes: BAREMETAL
      distro: K8S-1.21
      location: ON-PREM
      network-infra: ACI
      pod-network: ACI-CNI
