apiVersion: v1
data:
  machinegroupprofile_overrides: |
    extern_dynamic: 10.3.112.1/21
    extern_static: 10.4.112.1/21
    fabric_name: fabric14
    kubeapi_vlan: 101
    mcast_range:
      start: 225.114.1.1
      end: 225.114.255.255
    node_subnet: 1.100.101.1/24
    node_svc_subnet: 10.5.112.1/21
    pod_subnet: 10.2.0.1/16
    service_vlan: 102
kind: ConfigMap
metadata:
  labels:
    cluster: cluster-1
  name: k8s-1.21
  namespace: netop-manager
