apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: calicogf-calico-system-tigera-ca-bundle-configmap-core-v1
spec:
  clusterName: calicogf
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: tigera-ca-bundle
    namespace: calico-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"tigera-ca-bundle","namespace":"calico-system","creationTimestamp":null},"data":{"tigera-ca-bundle.crt":"#
    certificate name: tigera-ca-private\n-----BEGIN CERTIFICATE-----\nMIIDKTCCAhGgAwIBAgIIaTV/dUNpfRowDQYJKoZIhvcNAQELBQAwITEfMB0GA1UE\nAxMWdGlnZXJhLW9wZXJhdG9yLXNpZ25lcjAgFw0yMjEyMDYxMzIzMDNaGA8yMTIy\nMTExMjEzMjMwNFowITEfMB0GA1UEAxMWdGlnZXJhLW9wZXJhdG9yLXNpZ25lcjCC\nASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN8eiRGE+vcLqHuKbRBAKHUR\nigv3uw7nNr34hDkdKOAJKfGOCB3WsxEyYhExF6fWZYq4eJl5fA0Xt3kM591U3B+/\ng38NWNfMLk4BfuS02XInQsmLj6NTS8iHFoALL/kH/RSlvGv5qcct/gVs5KvuV68E\nckF2P1jPGXFbgCMKM3/KyGKxLGzOYds2cw8rCOx2NHQzXF8eoMiou0P/0jfHnHyV\nWC8sYU2iiv9kB381u+sRu+8UscNeKR9M23lcoQqYAfclvdjUlFxofd4vT8vWTbWF\nmWvipCNI/1mscQM09L8yVaH1H5ksBr6SPKDBd8C9s1z44S56RKKMhhXLDZhqoH0C\nAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O\nBBYEFIeOEEDRWHb0dCaHo8Dnhw9kqNuhMB8GA1UdIwQYMBaAFIeOEEDRWHb0dCaH\no8Dnhw9kqNuhMA0GCSqGSIb3DQEBCwUAA4IBAQAZhlCpUJliMiOpR9JDLcu4Born\nLfW8jLtIcTVQcjihQco1aMUs/jyLduvRKqO/9YW7yrAjL1x7AP4luxOiIBmjB1Im\naxWdMejkjDj1AVEnL5GBWaEq9ss9qDGCGd8plkhdKP3Z7VJsOz4ZXx9QG/czi98R\nbOhQyX36a8Dkxqh2OPMv0dqoDOwkL5AYrXkeXqV52+LRd2Hl0wh4RgHQ+9pg++ns\niXUiuJB27IJQneoZenDljt3yNNDMR4p86a5nW9GOchNXVk678pIuIBvSTPDJUpr+\nm5UMYc0C5QEv38HbvEgUXiZrSC5aV+z22bsnvMrHWbQMnG2NrodaQgf10Atq\n-----END
    CERTIFICATE-----\n\n\n"}}'
status:
  state: ""
