apiVersion: v1
data:
  status: |-
    {
      "cniStatus": {
        "config": "{\"uplink-iface\":\"eth0\",\"vxlan-iface\":\"eth0.3901\",\"vxlan-anycast-ip\":\"10.0.0.32\",\"opflex-peer-ip\":\"10.0.0.30\",\"uplink mac_adress\":\"00:50:56:97:7b:a6\",\"default-endpoint-group\":{\"policy-space\":\"pallavi\",\"name\":\"aci-containers-pallavi|aci-containers-default\"},\"default-qospolicy-group\":{},\"namespace-default-endpoint-group\":{\"aci-containers-system\":{\"policy-space\":\"pallavi\",\"name\":\"aci-containers-pallavi|aci-containers-system\"},\"istio-operator\":{\"policy-space\":\"pallavi\",\"name\":\"aci-containers-pallavi|aci-containers-istio\"},\"istio-system\":{\"policy-space\":\"pallavi\",\"name\":\"aci-containers-pallavi|aci-containers-istio\"},\"kube-system\":{\"policy-space\":\"pallavi\",\"name\":\"aci-containers-pallavi|aci-containers-system\"}},\"log-level\":\"debug\",\"node-name\":\"k8s22-node-1.local.lan\",\"status-port\":8090,\"grpc-port\":19999,\"cni-metadata-dir\":\"/usr/local/var/lib/aci-containers/\",\"cni-network\":\"k8s-pod-network\",\"opflex-config-path\":\"/usr/local/etc/opflex-agent-ovs/base-conf.d\",\"opflex-endpoint-dir\":\"/usr/local/var/lib/opflex-agent-ovs/endpoints/\",\"opflex-service-dir\":\"/usr/local/var/lib/opflex-agent-ovs/services/\",\"opflex-snat-dir\":\"/usr/local/var/lib/opflex-agent-ovs/snats/\",\"opflex-fault-dir\":\"/usr/local/var/lib/opflex-agent-ovs/faults/\",\"opflex-flowid-cache-dir\":\"/usr/local/var/lib/opflex-agent-ovs/ids/\",\"opflex-mcast-file\":\"/usr/local/var/lib/opflex-agent-ovs/mcast/opflex-groups.json\",\"opflex-server-config-file\":\"/usr/local/var/lib/opflex-server/config.json\",\"packet-event-notification-socket\":\"/usr/local/var/run/aci-containers-packet-event-notification.sock\",\"opflex-drop-log-config-dir\":\"/usr/local/var/lib/opflex-agent-ovs/droplog\",\"opflex-drop-log-remote-ip\":\"192.168.1.2\",\"ovs-db-sock\":\"/usr/local/var/run/openvswitch/db.sock\",\"ep-rpc-sock\":\"/usr/local/var/run/aci-containers-ep-rpc.sock\",\"aci-prefix\":\"pallavi\",\"aci-infra-vlan\":3901,\"service-vlan\":44,\"encap-type\":\"vxlan\",\"int-bridge-name\":\"br-int\",\"access-bridge-name\":\"br-access\",\"interface-mtu\":1700,\"interface-mtu-headroom\":100,\"cni-netconfig\":[{\"subnet\":\"10.2.0.0/16\",\"gateway\":\"10.2.0.1\",\"routes\":[{\"dst\":\"0.0.0.0/0\",\"gw\":\"10.2.0.1\"}]}],\"aci-vmm-type\":\"Kubernetes\",\"aci-vmm-domain\":\"pallavi\",\"aci-vmm-controller\":\"pallavi\",\"aci-vrf\":\"k8s22_vrf\",\"aci-vrf-tenant\":\"common\",\"zone\":8191,\"aci-snat-namespace\":\"aci-containers-system\",\"enable-drop-log\":true,\"drop-log-access-iface\":\"gen2\",\"drop-log-int-iface\":\"gen1\",\"drop-log-expiry\":10,\"drop-log-repeat-intvl\":2,\"flavor\":\"kubernetes-1.24\"}\n",
        "endpoints": "[]\n",
        "ipam": "{\"pod-ips\":{\"V4\":[{\"start\":\"10.2.0.130\",\"end\":\"10.2.0.161\"}]}}\n",
        "services": "[{\"uuid\":\"945fe9da-cd80-4f21-b3bd-23fd455631f1\",\"domain-policy-space\":\"common\",\"domain-name\":\"k8s22_vrf\",\"service-mode\":\"loadbalancer\",\"service-type\":\"clusterIp\",\"service-mapping\":[{\"service-ip\":\"10.110.166.174\",\"service-proto\":\"tcp\",\"service-port\":9995,\"next-hop-ips\":[\"10.2.0.3\",\"10.2.0.116\",\"10.2.0.60\"],\"next-hop-port\":8080,\"conntrack-enabled\":true,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}}],\"attributes\":{\"name\":\"nginx-svc-cip\",\"namespace\":\"nettools\",\"service-name\":\"nettools_nginx-svc-cip\",\"test-nginx-svc\":\"nginx-svc-cip\"}},{\"uuid\":\"c3de09cc-a1fe-432c-8a62-3354146d0e43\",\"domain-policy-space\":\"common\",\"domain-name\":\"k8s22_vrf\",\"service-mode\":\"loadbalancer\",\"service-type\":\"loadBalancer\",\"service-mapping\":[{\"service-ip\":\"10.110.99.191\",\"service-proto\":\"tcp\",\"service-port\":9995,\"next-hop-ips\":[\"10.2.0.3\",\"10.2.0.60\",\"10.2.0.116\"],\"next-hop-port\":8080,\"conntrack-enabled\":true,\"node-port\":31691,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}}],\"attributes\":{\"name\":\"nginx-svc-lb\",\"namespace\":\"nettools\",\"service-name\":\"nettools_nginx-svc-lb\",\"test-nginx-svc\":\"nginx-svc-lb\"}},{\"uuid\":\"67d3135c-1d79-4723-a71f-9529911fbd89\",\"domain-policy-space\":\"common\",\"domain-name\":\"k8s22_vrf\",\"service-mode\":\"loadbalancer\",\"service-type\":\"clusterIp\",\"service-mapping\":[{\"service-ip\":\"10.96.0.1\",\"service-proto\":\"tcp\",\"service-port\":443,\"next-hop-ips\":[\"192.168.22.2\"],\"next-hop-port\":6443,\"conntrack-enabled\":true,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}}],\"attributes\":{\"component\":\"apiserver\",\"name\":\"kubernetes\",\"namespace\":\"default\",\"provider\":\"kubernetes\",\"service-name\":\"default_kubernetes\"}},{\"uuid\":\"2767a96d-97ea-424a-926d-e71945e22fbe\",\"domain-policy-space\":\"common\",\"domain-name\":\"k8s22_vrf\",\"service-mode\":\"loadbalancer\",\"service-type\":\"clusterIp\",\"service-mapping\":[{\"service-ip\":\"10.96.0.10\",\"service-proto\":\"udp\",\"service-port\":53,\"next-hop-ips\":[\"10.2.0.68\",\"10.2.0.47\"],\"next-hop-port\":53,\"conntrack-enabled\":true,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}},{\"service-ip\":\"10.96.0.10\",\"service-proto\":\"tcp\",\"service-port\":53,\"next-hop-ips\":[\"10.2.0.68\",\"10.2.0.47\"],\"next-hop-port\":53,\"conntrack-enabled\":true,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}},{\"service-ip\":\"10.96.0.10\",\"service-proto\":\"tcp\",\"service-port\":9153,\"next-hop-ips\":[\"10.2.0.68\",\"10.2.0.47\"],\"next-hop-port\":9153,\"conntrack-enabled\":true,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}}],\"attributes\":{\"k8s-app\":\"kube-dns\",\"kubernetes.io/cluster-service\":\"true\",\"kubernetes.io/name\":\"CoreDNS\",\"name\":\"kube-dns\",\"namespace\":\"kube-system\",\"service-name\":\"kube-system_kube-dns\"}},{\"uuid\":\"cc4ef823-1504-419d-a380-c231b3ed7879\",\"domain-policy-space\":\"common\",\"domain-name\":\"k8s22_vrf\",\"service-mode\":\"loadbalancer\",\"service-type\":\"clusterIp\",\"service-mapping\":[{\"service-ip\":\"10.109.199.157\",\"service-proto\":\"tcp\",\"service-port\":8443,\"next-hop-ips\":[\"192.168.22.2\"],\"next-hop-port\":8443,\"conntrack-enabled\":true,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}}],\"attributes\":{\"control-plane\":\"controller-manager\",\"name\":\"netop-manager-controller-manager-metrics-service\",\"namespace\":\"netop-manager-system\",\"service-name\":\"netop-manager-system_netop-manager-controller-manager-metrics-service\"}},{\"uuid\":\"e6215791-4691-4203-867e-cd92610054ac\",\"domain-policy-space\":\"common\",\"domain-name\":\"k8s22_vrf\",\"service-mode\":\"loadbalancer\",\"service-type\":\"nodePort\",\"service-mapping\":[{\"service-ip\":\"10.103.132.110\",\"service-proto\":\"tcp\",\"service-port\":9995,\"next-hop-ips\":[\"10.2.0.3\",\"10.2.0.116\",\"10.2.0.60\"],\"next-hop-port\":8080,\"conntrack-enabled\":true,\"node-port\":32235,\"session-affinity\":{\"client-ip\":{\"timeout-seconds\":1}}}],\"attributes\":{\"name\":\"nginx-svc-nodeport\",\"namespace\":\"nettools\",\"service-name\":\"nettools_nginx-svc-nodeport\",\"test-nginx-svc\":\"nginx-svc-np\"}}]\n",
        "status": "{\"services\":6,\"pod-ips\":{\"V4\":[{\"start\":\"10.2.0.130\",\"end\":\"10.2.0.161\"}]}}\n"
      },
      "cniType": "cko-cni-aci",
      "cniVersion": "5.2.3.4",
      "ipam": "{\"pod-ips\":{\"V4\":[{\"start\":\"10.2.0.130\",\"end\":\"10.2.0.161\"}]}}\n",
      "observedGeneration": 1,
      "state": "Running",
      "upgradeStatus": {
        "cniUpgradeState": "None"
      }
    }
  status_b64: |-
    eyAiY25pU3RhdHVzIjogeyAiY29uZmlnIjogIntcInVwbGluay1pZmFjZVwiOlwiZXRoMFwiLFwidnhs
    YW4taWZhY2VcIjpcImV0aDAuMzkwMVwiLFwidnhsYW4tYW55Y2FzdC1pcFwiOlwiMTAuMC4wLjMyXCIs
    XCJvcGZsZXgtcGVlci1pcFwiOlwiMTAuMC4wLjMwXCIsXCJ1cGxpbmsgbWFjX2FkcmVzc1wiOlwiMDA6
    NTA6NTY6OTc6N2I6YTZcIixcImRlZmF1bHQtZW5kcG9pbnQtZ3JvdXBcIjp7XCJwb2xpY3ktc3BhY2Vc
    IjpcInBhbGxhdmlcIixcIm5hbWVcIjpcImFjaS1jb250YWluZXJzLXBhbGxhdml8YWNpLWNvbnRhaW5l
    cnMtZGVmYXVsdFwifSxcImRlZmF1bHQtcW9zcG9saWN5LWdyb3VwXCI6e30sXCJuYW1lc3BhY2UtZGVm
    YXVsdC1lbmRwb2ludC1ncm91cFwiOntcImFjaS1jb250YWluZXJzLXN5c3RlbVwiOntcInBvbGljeS1z
    cGFjZVwiOlwicGFsbGF2aVwiLFwibmFtZVwiOlwiYWNpLWNvbnRhaW5lcnMtcGFsbGF2aXxhY2ktY29u
    dGFpbmVycy1zeXN0ZW1cIn0sXCJpc3Rpby1vcGVyYXRvclwiOntcInBvbGljeS1zcGFjZVwiOlwicGFs
    bGF2aVwiLFwibmFtZVwiOlwiYWNpLWNvbnRhaW5lcnMtcGFsbGF2aXxhY2ktY29udGFpbmVycy1pc3Rp
    b1wifSxcImlzdGlvLXN5c3RlbVwiOntcInBvbGljeS1zcGFjZVwiOlwicGFsbGF2aVwiLFwibmFtZVwi
    OlwiYWNpLWNvbnRhaW5lcnMtcGFsbGF2aXxhY2ktY29udGFpbmVycy1pc3Rpb1wifSxcImt1YmUtc3lz
    dGVtXCI6e1wicG9saWN5LXNwYWNlXCI6XCJwYWxsYXZpXCIsXCJuYW1lXCI6XCJhY2ktY29udGFpbmVy
    cy1wYWxsYXZpfGFjaS1jb250YWluZXJzLXN5c3RlbVwifX0sXCJsb2ctbGV2ZWxcIjpcImRlYnVnXCIs
    XCJub2RlLW5hbWVcIjpcIms4czIyLW5vZGUtMS5sb2NhbC5sYW5cIixcInN0YXR1cy1wb3J0XCI6ODA5
    MCxcImdycGMtcG9ydFwiOjE5OTk5LFwiY25pLW1ldGFkYXRhLWRpclwiOlwiL3Vzci9sb2NhbC92YXIv
    bGliL2FjaS1jb250YWluZXJzL1wiLFwiY25pLW5ldHdvcmtcIjpcIms4cy1wb2QtbmV0d29ya1wiLFwi
    b3BmbGV4LWNvbmZpZy1wYXRoXCI6XCIvdXNyL2xvY2FsL2V0Yy9vcGZsZXgtYWdlbnQtb3ZzL2Jhc2Ut
    Y29uZi5kXCIsXCJvcGZsZXgtZW5kcG9pbnQtZGlyXCI6XCIvdXNyL2xvY2FsL3Zhci9saWIvb3BmbGV4
    LWFnZW50LW92cy9lbmRwb2ludHMvXCIsXCJvcGZsZXgtc2VydmljZS1kaXJcIjpcIi91c3IvbG9jYWwv
    dmFyL2xpYi9vcGZsZXgtYWdlbnQtb3ZzL3NlcnZpY2VzL1wiLFwib3BmbGV4LXNuYXQtZGlyXCI6XCIv
    dXNyL2xvY2FsL3Zhci9saWIvb3BmbGV4LWFnZW50LW92cy9zbmF0cy9cIixcIm9wZmxleC1mYXVsdC1k
    aXJcIjpcIi91c3IvbG9jYWwvdmFyL2xpYi9vcGZsZXgtYWdlbnQtb3ZzL2ZhdWx0cy9cIixcIm9wZmxl
    eC1mbG93aWQtY2FjaGUtZGlyXCI6XCIvdXNyL2xvY2FsL3Zhci9saWIvb3BmbGV4LWFnZW50LW92cy9p
    ZHMvXCIsXCJvcGZsZXgtbWNhc3QtZmlsZVwiOlwiL3Vzci9sb2NhbC92YXIvbGliL29wZmxleC1hZ2Vu
    dC1vdnMvbWNhc3Qvb3BmbGV4LWdyb3Vwcy5qc29uXCIsXCJvcGZsZXgtc2VydmVyLWNvbmZpZy1maWxl
    XCI6XCIvdXNyL2xvY2FsL3Zhci9saWIvb3BmbGV4LXNlcnZlci9jb25maWcuanNvblwiLFwicGFja2V0
    LWV2ZW50LW5vdGlmaWNhdGlvbi1zb2NrZXRcIjpcIi91c3IvbG9jYWwvdmFyL3J1bi9hY2ktY29udGFp
    bmVycy1wYWNrZXQtZXZlbnQtbm90aWZpY2F0aW9uLnNvY2tcIixcIm9wZmxleC1kcm9wLWxvZy1jb25m
    aWctZGlyXCI6XCIvdXNyL2xvY2FsL3Zhci9saWIvb3BmbGV4LWFnZW50LW92cy9kcm9wbG9nXCIsXCJv
    cGZsZXgtZHJvcC1sb2ctcmVtb3RlLWlwXCI6XCIxOTIuMTY4LjEuMlwiLFwib3ZzLWRiLXNvY2tcIjpc
    Ii91c3IvbG9jYWwvdmFyL3J1bi9vcGVudnN3aXRjaC9kYi5zb2NrXCIsXCJlcC1ycGMtc29ja1wiOlwi
    L3Vzci9sb2NhbC92YXIvcnVuL2FjaS1jb250YWluZXJzLWVwLXJwYy5zb2NrXCIsXCJhY2ktcHJlZml4
    XCI6XCJwYWxsYXZpXCIsXCJhY2ktaW5mcmEtdmxhblwiOjM5MDEsXCJzZXJ2aWNlLXZsYW5cIjo0NCxc
    ImVuY2FwLXR5cGVcIjpcInZ4bGFuXCIsXCJpbnQtYnJpZGdlLW5hbWVcIjpcImJyLWludFwiLFwiYWNj
    ZXNzLWJyaWRnZS1uYW1lXCI6XCJici1hY2Nlc3NcIixcImludGVyZmFjZS1tdHVcIjoxNzAwLFwiaW50
    ZXJmYWNlLW10dS1oZWFkcm9vbVwiOjEwMCxcImNuaS1uZXRjb25maWdcIjpbe1wic3VibmV0XCI6XCIx
    MC4yLjAuMC8xNlwiLFwiZ2F0ZXdheVwiOlwiMTAuMi4wLjFcIixcInJvdXRlc1wiOlt7XCJkc3RcIjpc
    IjAuMC4wLjAvMFwiLFwiZ3dcIjpcIjEwLjIuMC4xXCJ9XX1dLFwiYWNpLXZtbS10eXBlXCI6XCJLdWJl
    cm5ldGVzXCIsXCJhY2ktdm1tLWRvbWFpblwiOlwicGFsbGF2aVwiLFwiYWNpLXZtbS1jb250cm9sbGVy
    XCI6XCJwYWxsYXZpXCIsXCJhY2ktdnJmXCI6XCJrOHMyMl92cmZcIixcImFjaS12cmYtdGVuYW50XCI6
    XCJjb21tb25cIixcInpvbmVcIjo4MTkxLFwiYWNpLXNuYXQtbmFtZXNwYWNlXCI6XCJhY2ktY29udGFp
    bmVycy1zeXN0ZW1cIixcImVuYWJsZS1kcm9wLWxvZ1wiOnRydWUsXCJkcm9wLWxvZy1hY2Nlc3MtaWZh
    Y2VcIjpcImdlbjJcIixcImRyb3AtbG9nLWludC1pZmFjZVwiOlwiZ2VuMVwiLFwiZHJvcC1sb2ctZXhw
    aXJ5XCI6MTAsXCJkcm9wLWxvZy1yZXBlYXQtaW50dmxcIjoyLFwiZmxhdm9yXCI6XCJrdWJlcm5ldGVz
    LTEuMjRcIn1cbiIsICJlbmRwb2ludHMiOiAiW11cbiIsICJpcGFtIjogIntcInBvZC1pcHNcIjp7XCJW
    NFwiOlt7XCJzdGFydFwiOlwiMTAuMi4wLjEzMFwiLFwiZW5kXCI6XCIxMC4yLjAuMTYxXCJ9XX19XG4i
    LCAic2VydmljZXMiOiAiW3tcInV1aWRcIjpcIjk0NWZlOWRhLWNkODAtNGYyMS1iM2JkLTIzZmQ0NTU2
    MzFmMVwiLFwiZG9tYWluLXBvbGljeS1zcGFjZVwiOlwiY29tbW9uXCIsXCJkb21haW4tbmFtZVwiOlwi
    azhzMjJfdnJmXCIsXCJzZXJ2aWNlLW1vZGVcIjpcImxvYWRiYWxhbmNlclwiLFwic2VydmljZS10eXBl
    XCI6XCJjbHVzdGVySXBcIixcInNlcnZpY2UtbWFwcGluZ1wiOlt7XCJzZXJ2aWNlLWlwXCI6XCIxMC4x
    MTAuMTY2LjE3NFwiLFwic2VydmljZS1wcm90b1wiOlwidGNwXCIsXCJzZXJ2aWNlLXBvcnRcIjo5OTk1
    LFwibmV4dC1ob3AtaXBzXCI6W1wiMTAuMi4wLjNcIixcIjEwLjIuMC4xMTZcIixcIjEwLjIuMC42MFwi
    XSxcIm5leHQtaG9wLXBvcnRcIjo4MDgwLFwiY29ubnRyYWNrLWVuYWJsZWRcIjp0cnVlLFwic2Vzc2lv
    bi1hZmZpbml0eVwiOntcImNsaWVudC1pcFwiOntcInRpbWVvdXQtc2Vjb25kc1wiOjF9fX1dLFwiYXR0
    cmlidXRlc1wiOntcIm5hbWVcIjpcIm5naW54LXN2Yy1jaXBcIixcIm5hbWVzcGFjZVwiOlwibmV0dG9v
    bHNcIixcInNlcnZpY2UtbmFtZVwiOlwibmV0dG9vbHNfbmdpbngtc3ZjLWNpcFwiLFwidGVzdC1uZ2lu
    eC1zdmNcIjpcIm5naW54LXN2Yy1jaXBcIn19LHtcInV1aWRcIjpcImMzZGUwOWNjLWExZmUtNDMyYy04
    YTYyLTMzNTQxNDZkMGU0M1wiLFwiZG9tYWluLXBvbGljeS1zcGFjZVwiOlwiY29tbW9uXCIsXCJkb21h
    aW4tbmFtZVwiOlwiazhzMjJfdnJmXCIsXCJzZXJ2aWNlLW1vZGVcIjpcImxvYWRiYWxhbmNlclwiLFwi
    c2VydmljZS10eXBlXCI6XCJsb2FkQmFsYW5jZXJcIixcInNlcnZpY2UtbWFwcGluZ1wiOlt7XCJzZXJ2
    aWNlLWlwXCI6XCIxMC4xMTAuOTkuMTkxXCIsXCJzZXJ2aWNlLXByb3RvXCI6XCJ0Y3BcIixcInNlcnZp
    Y2UtcG9ydFwiOjk5OTUsXCJuZXh0LWhvcC1pcHNcIjpbXCIxMC4yLjAuM1wiLFwiMTAuMi4wLjYwXCIs
    XCIxMC4yLjAuMTE2XCJdLFwibmV4dC1ob3AtcG9ydFwiOjgwODAsXCJjb25udHJhY2stZW5hYmxlZFwi
    OnRydWUsXCJub2RlLXBvcnRcIjozMTY5MSxcInNlc3Npb24tYWZmaW5pdHlcIjp7XCJjbGllbnQtaXBc
    Ijp7XCJ0aW1lb3V0LXNlY29uZHNcIjoxfX19XSxcImF0dHJpYnV0ZXNcIjp7XCJuYW1lXCI6XCJuZ2lu
    eC1zdmMtbGJcIixcIm5hbWVzcGFjZVwiOlwibmV0dG9vbHNcIixcInNlcnZpY2UtbmFtZVwiOlwibmV0
    dG9vbHNfbmdpbngtc3ZjLWxiXCIsXCJ0ZXN0LW5naW54LXN2Y1wiOlwibmdpbngtc3ZjLWxiXCJ9fSx7
    XCJ1dWlkXCI6XCI2N2QzMTM1Yy0xZDc5LTQ3MjMtYTcxZi05NTI5OTExZmJkODlcIixcImRvbWFpbi1w
    b2xpY3ktc3BhY2VcIjpcImNvbW1vblwiLFwiZG9tYWluLW5hbWVcIjpcIms4czIyX3ZyZlwiLFwic2Vy
    dmljZS1tb2RlXCI6XCJsb2FkYmFsYW5jZXJcIixcInNlcnZpY2UtdHlwZVwiOlwiY2x1c3RlcklwXCIs
    XCJzZXJ2aWNlLW1hcHBpbmdcIjpbe1wic2VydmljZS1pcFwiOlwiMTAuOTYuMC4xXCIsXCJzZXJ2aWNl
    LXByb3RvXCI6XCJ0Y3BcIixcInNlcnZpY2UtcG9ydFwiOjQ0MyxcIm5leHQtaG9wLWlwc1wiOltcIjE5
    Mi4xNjguMjIuMlwiXSxcIm5leHQtaG9wLXBvcnRcIjo2NDQzLFwiY29ubnRyYWNrLWVuYWJsZWRcIjp0
    cnVlLFwic2Vzc2lvbi1hZmZpbml0eVwiOntcImNsaWVudC1pcFwiOntcInRpbWVvdXQtc2Vjb25kc1wi
    OjF9fX1dLFwiYXR0cmlidXRlc1wiOntcImNvbXBvbmVudFwiOlwiYXBpc2VydmVyXCIsXCJuYW1lXCI6
    XCJrdWJlcm5ldGVzXCIsXCJuYW1lc3BhY2VcIjpcImRlZmF1bHRcIixcInByb3ZpZGVyXCI6XCJrdWJl
    cm5ldGVzXCIsXCJzZXJ2aWNlLW5hbWVcIjpcImRlZmF1bHRfa3ViZXJuZXRlc1wifX0se1widXVpZFwi
    OlwiMjc2N2E5NmQtOTdlYS00MjRhLTkyNmQtZTcxOTQ1ZTIyZmJlXCIsXCJkb21haW4tcG9saWN5LXNw
    YWNlXCI6XCJjb21tb25cIixcImRvbWFpbi1uYW1lXCI6XCJrOHMyMl92cmZcIixcInNlcnZpY2UtbW9k
    ZVwiOlwibG9hZGJhbGFuY2VyXCIsXCJzZXJ2aWNlLXR5cGVcIjpcImNsdXN0ZXJJcFwiLFwic2Vydmlj
    ZS1tYXBwaW5nXCI6W3tcInNlcnZpY2UtaXBcIjpcIjEwLjk2LjAuMTBcIixcInNlcnZpY2UtcHJvdG9c
    IjpcInVkcFwiLFwic2VydmljZS1wb3J0XCI6NTMsXCJuZXh0LWhvcC1pcHNcIjpbXCIxMC4yLjAuNjhc
    IixcIjEwLjIuMC40N1wiXSxcIm5leHQtaG9wLXBvcnRcIjo1MyxcImNvbm50cmFjay1lbmFibGVkXCI6
    dHJ1ZSxcInNlc3Npb24tYWZmaW5pdHlcIjp7XCJjbGllbnQtaXBcIjp7XCJ0aW1lb3V0LXNlY29uZHNc
    IjoxfX19LHtcInNlcnZpY2UtaXBcIjpcIjEwLjk2LjAuMTBcIixcInNlcnZpY2UtcHJvdG9cIjpcInRj
    cFwiLFwic2VydmljZS1wb3J0XCI6NTMsXCJuZXh0LWhvcC1pcHNcIjpbXCIxMC4yLjAuNjhcIixcIjEw
    LjIuMC40N1wiXSxcIm5leHQtaG9wLXBvcnRcIjo1MyxcImNvbm50cmFjay1lbmFibGVkXCI6dHJ1ZSxc
    InNlc3Npb24tYWZmaW5pdHlcIjp7XCJjbGllbnQtaXBcIjp7XCJ0aW1lb3V0LXNlY29uZHNcIjoxfX19
    LHtcInNlcnZpY2UtaXBcIjpcIjEwLjk2LjAuMTBcIixcInNlcnZpY2UtcHJvdG9cIjpcInRjcFwiLFwi
    c2VydmljZS1wb3J0XCI6OTE1MyxcIm5leHQtaG9wLWlwc1wiOltcIjEwLjIuMC42OFwiLFwiMTAuMi4w
    LjQ3XCJdLFwibmV4dC1ob3AtcG9ydFwiOjkxNTMsXCJjb25udHJhY2stZW5hYmxlZFwiOnRydWUsXCJz
    ZXNzaW9uLWFmZmluaXR5XCI6e1wiY2xpZW50LWlwXCI6e1widGltZW91dC1zZWNvbmRzXCI6MX19fV0s
    XCJhdHRyaWJ1dGVzXCI6e1wiazhzLWFwcFwiOlwia3ViZS1kbnNcIixcImt1YmVybmV0ZXMuaW8vY2x1
    c3Rlci1zZXJ2aWNlXCI6XCJ0cnVlXCIsXCJrdWJlcm5ldGVzLmlvL25hbWVcIjpcIkNvcmVETlNcIixc
    Im5hbWVcIjpcImt1YmUtZG5zXCIsXCJuYW1lc3BhY2VcIjpcImt1YmUtc3lzdGVtXCIsXCJzZXJ2aWNl
    LW5hbWVcIjpcImt1YmUtc3lzdGVtX2t1YmUtZG5zXCJ9fSx7XCJ1dWlkXCI6XCJjYzRlZjgyMy0xNTA0
    LTQxOWQtYTM4MC1jMjMxYjNlZDc4NzlcIixcImRvbWFpbi1wb2xpY3ktc3BhY2VcIjpcImNvbW1vblwi
    LFwiZG9tYWluLW5hbWVcIjpcIms4czIyX3ZyZlwiLFwic2VydmljZS1tb2RlXCI6XCJsb2FkYmFsYW5j
    ZXJcIixcInNlcnZpY2UtdHlwZVwiOlwiY2x1c3RlcklwXCIsXCJzZXJ2aWNlLW1hcHBpbmdcIjpbe1wi
    c2VydmljZS1pcFwiOlwiMTAuMTA5LjE5OS4xNTdcIixcInNlcnZpY2UtcHJvdG9cIjpcInRjcFwiLFwi
    c2VydmljZS1wb3J0XCI6ODQ0MyxcIm5leHQtaG9wLWlwc1wiOltcIjE5Mi4xNjguMjIuMlwiXSxcIm5l
    eHQtaG9wLXBvcnRcIjo4NDQzLFwiY29ubnRyYWNrLWVuYWJsZWRcIjp0cnVlLFwic2Vzc2lvbi1hZmZp
    bml0eVwiOntcImNsaWVudC1pcFwiOntcInRpbWVvdXQtc2Vjb25kc1wiOjF9fX1dLFwiYXR0cmlidXRl
    c1wiOntcImNvbnRyb2wtcGxhbmVcIjpcImNvbnRyb2xsZXItbWFuYWdlclwiLFwibmFtZVwiOlwibmV0
    b3AtbWFuYWdlci1jb250cm9sbGVyLW1hbmFnZXItbWV0cmljcy1zZXJ2aWNlXCIsXCJuYW1lc3BhY2Vc
    IjpcIm5ldG9wLW1hbmFnZXItc3lzdGVtXCIsXCJzZXJ2aWNlLW5hbWVcIjpcIm5ldG9wLW1hbmFnZXIt
    c3lzdGVtX25ldG9wLW1hbmFnZXItY29udHJvbGxlci1tYW5hZ2VyLW1ldHJpY3Mtc2VydmljZVwifX0s
    e1widXVpZFwiOlwiZTYyMTU3OTEtNDY5MS00MjAzLTg2N2UtY2Q5MjYxMDA1NGFjXCIsXCJkb21haW4t
    cG9saWN5LXNwYWNlXCI6XCJjb21tb25cIixcImRvbWFpbi1uYW1lXCI6XCJrOHMyMl92cmZcIixcInNl
    cnZpY2UtbW9kZVwiOlwibG9hZGJhbGFuY2VyXCIsXCJzZXJ2aWNlLXR5cGVcIjpcIm5vZGVQb3J0XCIs
    XCJzZXJ2aWNlLW1hcHBpbmdcIjpbe1wic2VydmljZS1pcFwiOlwiMTAuMTAzLjEzMi4xMTBcIixcInNl
    cnZpY2UtcHJvdG9cIjpcInRjcFwiLFwic2VydmljZS1wb3J0XCI6OTk5NSxcIm5leHQtaG9wLWlwc1wi
    OltcIjEwLjIuMC4zXCIsXCIxMC4yLjAuMTE2XCIsXCIxMC4yLjAuNjBcIl0sXCJuZXh0LWhvcC1wb3J0
    XCI6ODA4MCxcImNvbm50cmFjay1lbmFibGVkXCI6dHJ1ZSxcIm5vZGUtcG9ydFwiOjMyMjM1LFwic2Vz
    c2lvbi1hZmZpbml0eVwiOntcImNsaWVudC1pcFwiOntcInRpbWVvdXQtc2Vjb25kc1wiOjF9fX1dLFwi
    YXR0cmlidXRlc1wiOntcIm5hbWVcIjpcIm5naW54LXN2Yy1ub2RlcG9ydFwiLFwibmFtZXNwYWNlXCI6
    XCJuZXR0b29sc1wiLFwic2VydmljZS1uYW1lXCI6XCJuZXR0b29sc19uZ2lueC1zdmMtbm9kZXBvcnRc
    IixcInRlc3Qtbmdpbngtc3ZjXCI6XCJuZ2lueC1zdmMtbnBcIn19XVxuIiwgInN0YXR1cyI6ICJ7XCJz
    ZXJ2aWNlc1wiOjYsXCJwb2QtaXBzXCI6e1wiVjRcIjpbe1wic3RhcnRcIjpcIjEwLjIuMC4xMzBcIixc
    ImVuZFwiOlwiMTAuMi4wLjE2MVwifV19fVxuIiB9LCAiY25pVHlwZSI6ICJja28tY25pLWFjaSIsICJj
    bmlWZXJzaW9uIjogIjUuMi4zLjQiLCAiaXBhbSI6ICJ7XCJwb2QtaXBzXCI6e1wiVjRcIjpbe1wic3Rh
    cnRcIjpcIjEwLjIuMC4xMzBcIixcImVuZFwiOlwiMTAuMi4wLjE2MVwifV19fVxuIiwgIm9ic2VydmVk
    R2VuZXJhdGlvbiI6IDEsICJzdGF0ZSI6ICJSdW5uaW5nIiwgInVwZ3JhZGVTdGF0dXMiOiB7ICJjbmlV
    cGdyYWRlU3RhdGUiOiAiTm9uZSIgfSB9Cg==
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: cko-cni-cko-cni-aci
  name: pallavi-cko-cni-cko-cni-aci
  namespace: 
