apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: clpod1-calico-system-noiro-docker-registry-secret-secret-core-v1
spec:
  clusterName: clpod1
  objRef:
    apiVersion: v1
    kind: Secret
    name: noiro-docker-registry-secret
    namespace: calico-system
  serializedObj: '{"kind":"Secret","apiVersion":"v1","metadata":{"name":"noiro-docker-registry-secret","namespace":"calico-system","creationTimestamp":null},"data":{".dockerconfigjson":"eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmd2FyZHppYyIsInBhc3N3b3JkIjoiTDFvbnNAc3ZzIiwiZW1haWwiOiJmd2FyZHppY0BjaXNjby5jb20iLCJhdXRoIjoiWm5kaGNtUjZhV002VERGdmJuTkFjM1p6In19fQ=="},"type":"kubernetes.io/dockerconfigjson"}'
status:
  state: ""
