apiVersion: v1
data:
  clusterprofile_overrides: |
    machine_group_profile_name: for-calico-cni
    cluster_input:
      registry:
        image_prefix: quay.io/noirolabs
      calico_config:
        net_config:
          encapsulation: None
        bgp_peer_config:
          remote_as_number: 650011
          local_as_number: 64512
          racks:
            - [2.100.101.201, 2.100.101.202]
      net_config:
        node_subnet: 2.100.101.1/24
        pod_subnet: 20.2.0.1/16
        extern_dynamic: 20.3.0.1/16
        cluster_svc_subnet: 10.96.0.0/12
      service_mesh_config:
        mesh_id: bm2calico
        network: network2
        mesh_id: mesh1
        role: Primary
        kubeconfig: https://github.com/networkoperator/demo-clusters/tree/kiran/calico-aci-cluster
      monitoring_config:
        monitoring_type: prometheus
        remote_write_ip: 3.237.37.136
        remote_write_port: 32307
      lb_config:
        lb_type: metallb
      cko_proxy_config:
        http_proxy: http://proxy.esl.cisco.com:80
        https_proxy: http://proxy.esl.cisco.com:80
        no_proxy: 10.96.0.1
kind: ConfigMap
metadata:
  labels:
    distro: kubernetes
    location: on-prem
    pod_network: calico
  name: bm2calico
  namespace: netop-manager
